version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build: ./apps/backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  data-worker:
    build: ./apps/data-worker
    container_name: data-worker
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./apps/shared:/app/shared
      - ./storage:/app/storage
    depends_on:
      - backend

  llm-worker:
    build: ./apps/llm-worker
    container_name: llm-worker
    ports:
      - "8001:8001"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - backend
      - redis
    volumes:
      - ./apps/shared:/app/shared
      - ./storage:/app/storage

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
