services:
  db:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  backend:
    build: ./src/backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  llm-api:
    build: ./src/llm-api
    container_name: llm-api
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - backend

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
