paths:
  raw_data: 'datasets'
  models: 'models'
  model_logs_dir: 'logs'

files_name:
  genbank:
    annotations: 'genbank/gb_curated.gb'
  gencode:
    annotations: 'gencode/file1.gtf'
    fasta: 'gencode/file1.fa'

data_extraction:
  save_batch_len: 2000

datasets_lengths:
  EXINCLASSIFIER:
    gpt: 512
    bert: 256
    dnabert: 256
  TRIPLETCLASSIFIER:
    bert: 2048
    dnabert: 2048
  DNATRANSLATOR:
    gpt: 512

dataset_generation:
  batch_size: 2000
