paths:
  raw_data: 'datasets'
  models: 'models'
  model_logs_dir: 'logs'

files_name:
  genbank:
    annotations: 'genbank/gb_curated.gb'
  gencode:
    annotations: 'gencode/file1.gtf'
    fasta: 'gencode/file1.fa'

data_extraction:
  save_batch_len: 2000
  extraction_max_len: 416

dataset_generation:
  batch_size: 5000
