from enum import Enum


class ModelEnum(str, Enum):
  GPT = "GPT"
  BERT = "BERT"
  DNABERT = "DNABERT"
  T5 = "T5"

class ApproachEnum(str, Enum):
  EXINCLASSIFIER = "EXINCLASSIFIER"
  SLIDINGWINDOWEXTRACTION = "SLIDINGWINDOWEXTRACTION"
  PROTEINTRANSLATOR = "PROTEINTRANSLATOR"
