FROM nvidia/cuda:12.1.0-runtime-ubuntu22.04

RUN apt update && apt install -y python3 python3-pip git curl build-essential

RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -
ENV PATH="/root/.local/bin:$PATH"
ENV PDM_IGNORE_SAVED_PYTHON=1

WORKDIR /app
COPY pyproject.toml pdm.lock ./
RUN pdm install --no-dev

COPY . .

ENV PYTHONPATH="/app:/app/../shared"

CMD bash -c "pdm run initialize && pdm run start"