FROM python:3.10-slim

RUN apt update && apt install -y curl git build-essential

RUN curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -

ENV PATH="/root/.local/bin:$PATH"
ENV PDM_IGNORE_SAVED_PYTHON=1

WORKDIR /app

COPY pyproject.toml pdm.lock ./

RUN pdm install --no-dev

COPY . .

ENV PYTHONPATH="/app:/app/../shared"

CMD ["pdm", "run", "start"]
